---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: "jdbc:h2:mem:bookmarksdb;INIT=CREATE SCHEMA IF NOT EXISTS BOOKMARKS;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: "sa"
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        default_schema: bookmarks
    hibernate:
      ddl-auto: create-drop
      